# Generated by ORMatic

from __future__ import annotations
from sqlalchemy import Column, ForeignKey, Integer, String, Float, Boolean, DateTime, Enum, JSON
from sqlalchemy.orm import relationship, Mapped, mapped_column, DeclarativeBase

import krrood.entity_query_language.predicate
import typing


from krrood.ormatic.dao import DataAccessObject
from krrood.ormatic.custom_types import TypeType

class Base(DeclarativeBase):
    type_mappings = {
    }


class PredicateDAO(Base, DataAccessObject[krrood.entity_query_language.predicate.Predicate]):

    __tablename__ = 'PredicateDAO'

    database_id: Mapped[builtins.int] = mapped_column(Integer, primary_key=True, use_existing_column=True)







